### ISSUE TITLE
SEV ILIAS 8: wenn ein Tn ein Pflichtfreld nicht ausfüllt, gelangt er auf die nächste Seite (erst dort wird rote Meldung gezeigt)

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#10]
**Describe the bug**
Füllt ein Tn ein Plfichtfeld nicht aus, führt ihn das SEV direkt uf die nächste Seite (BUG). Erst dort wird ihm der Rote Hinweis (fehlendes Pflichtfeld) angezeit. 

**To Reproduce**
1. Als Tn (Lara Blum) oder Anonymous öffnen: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html
2. Im Stammdatenblock ein Pflichfeld auslassen und auf "weiter" klicken. 

**Expected behavior**
Der User bleibt auf der gleichen Seite, es erscheint der rote Hinweis. Das Plichtfeld mit fehlendem Eintrag ist rot markiert. Alle weitere eingegebenen Formulardaten sind weiterhin eingegeben. 

**Screenshots**
User befindet sich auf der nächsten Seite: 
<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/64cbe05d-c85a-4123-a0f1-a31c20280ee8">

**Comment by okaufman** [comment]
Ist wahrscheinlich verwandt mit #14

**Comment by okaufman** [comment]
ist gefixt
