### ISSUE TITLE
SEV ILIAS 8: Whoops, wenn vorgängig erzeugte Identifikation eingegeben wird

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#11]
**Describe the bug**
Wenn bei Zugriff als Anonymous eine zuvor erzeugte Identifikationsnummer eingegeben wird --> Whoops

In meinem Beispiel hatte ich die Identifikationsnummer "775895".

**Expected behavior**
Ein neuer Durchlauf wird gestartet.

**Screenshots**

<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/7c5a10e2-75c9-4cf2-9614-3d162db26e4c">

<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/9a480d18-7397-440e-afb4-033aa0102651">

Fehlermeldung: 
ilub\plugin\SelfEvaluation\Identity\Identity::_getInstanceForObjIdAndIdentifier(): Argument #3 ($identifier) must be of type int, string given, called in /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/SelfEvaluation/classes/class.IdentityGUI.php on line 100

**Comment by okaufman** [comment]
geht jetzt wieder
