### ISSUE TITLE
SEV ILIAS 8: Frageblöcke-Feedbacks können nicht bearbeitet werden

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#12]
**Describe the bug**
In https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577635.html habe ich soeben ein Gesamtfeedback eingerichtet. 

Wenn ich dann/später bei einem einem Frageblock das Feedback eines einzelnen Frageblocks bearbeiten möchte, werden mir die Werte des zuvor eingerichteten Gesamtfeedbacks angezeigt.

Seltsam ist auch, dass in der Ansicht **der Titel des Frageblocks** nicht angezeigt wird (siehe markiert Stelle beim ":")

**To Reproduce**
Siehe Link oben. 

**Screenshots**
<img width="600" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/4ba26232-5d8a-4b33-9d29-4c2a7231312b">

**Comment by okaufman** [comment]
Das konnte ich fixen.
