### ISSUE TITLE
SEV ILIAS 8: Whoops, wenn Tn auf letzter Seite/vor Schluss auf "Speichern" klickt

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#13]
**Describe the bug**
hier getestet: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html

Wenn ich mit dem Kursmitglied Lara Blum das SEV durcharbeite und am Schluss auf der letzten Seite auf "Speichern" klicke, Whoops das Ding ordentlich. 

**Expected behavior**
SEV führt auf die Resultate-Seite.

**Screenshots**
<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/0ccd548b-1d93-47b7-9d7d-b8da6edf8af2">

<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/680e47ac-95d0-44f2-832c-cafa584d4e60">

Fehlermeldung: 
ilButton::getForm(): Return value must be of type string, null returned

**Comment by okaufman** [comment]
Den Fehler habe ich korrigiert mit einem Patch im core.
