### ISSUE TITLE
SEV ILIAS 8: Auch wenn Tn alle Pflichfelder ausfüllt, wird (auf Folgeseite) Fehlermeldung angezeigt

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#14]
**Describe the bug**
Siehe Video. 
Auch wenn Tn alle Pflichtfelder einer Seite ausfüllt, erscheint auf der kommenden Seite die rote Meldung "Einige Angaben sind unvollständig oder ungültig. Bitte korrigieren Sie Ihre Eingabe."
Komisch erscheint mir auch, dass Pflichtfelder beim ersten Aufruf bzw. noch vor dem Ausfüllen an rot markiert sind oder der Hinweis steht " Dieses Feld muss ausgefüllt werden. Bitte geben Sie etwas ein."

**To Reproduce**
Siehe Video.  Gestetet mit Kursmitglied Lara Blum hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html

**Screenshots**

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/5e25bd88-d3a5-4597-888f-679c95aaf571

**Comment by okaufman** [comment]
fixed
