### ISSUE TITLE
SEV ILIAS 8: Whoops, wenn im Tab "Resultate" auf eine Benutzerkennung/Username geklickt wird

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#15]
**Describe the bug**
Whoops, wenn im Tab "Resultate" auf eine Benutzerkennung/Username geklickt wird. Siehe Screenshot.

Bug wohl verknüpft mit: https://github.com/ilub-unibe-ch/SelfEvaluation/issues/13 

**Expected behavior**
SEV führt auf die Feedbackseite des Benutzers.

**Screenshots**
<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/37182cea-66f8-489f-a769-f462457241de">

<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/1de93d07-21c5-4aeb-950c-21b776f2a7b7">

**Comment by okaufman** [comment]
Das geht jetzt mit dem Fix von #13
