### ISSUE TITLE
SEV ILIAS 8: Löschen einzelner Resultate/Durchührungen nicht möglich ("Es wurde kein Datensatz ausgewählt.")

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#16]
**Describe the bug**
In der Listenansicht der Resultate/Durchführungen im Tab "Resultate" ist es nicht möglich, einzelne Durchführungen zu löschen. 
Obwohl ein Eintrag angewählt ist, und auf Button "Datensatz Löschen" geklickt wird, meldet ILIAS: "Es wurde kein Datensatz ausgewählt."

**Screenshots**
<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/1c766986-b398-46b6-b591-5af9aabc72c5">

**Comment by okaufman** [comment]
gefixt
