### ISSUE TITLE
SEV ILIAS 8: Whoops, wenn versucht wird, ein einzelnes Resultatezu löschen (über "Aktionen" --> "Datensatz Löschen")

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#17]
**Describe the bug**
im Tab "Resultate".
Aktion "Aktionen" --> "Datensatz Löschen" führt zu Whoops

ilConfirmationGUI::addItem(): Argument #2 ($a_id) must be of type string, int given, called in /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/SelfEvaluation/classes/class.DatasetGUI.php on line 151

Screenshots:
<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/d6b15a4b-50b3-45b0-8b95-1abda0f5d34c">

<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/82f2ccae-1372-4db9-a02a-cba71932b5e4">

**Comment by okaufman** [comment]
das geht jetzt
