### ISSUE TITLE
SEV ILIAS 8: Klick auf "Als csv exportieren" im Tab "Resultate" löst nichts aus

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#18]
**Describe the bug**
Klick auf "Als csv exportieren" im Tab "Resultate" löst nichts aus. Bei mir öffnet sich einfach ein neuer Tab, und nichts geschieht. 
Getestet hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html

**Expected behavior**
Es wird eine csv Datei mit den Tabellendaten erzeugt. 

**Screenshots**
<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/a1a9d59c-597c-440b-80dd-16dd9f0f7a36">

**Additional context**
Evtl. ist das Problem in meinem Test, dass noch kein Durchlauf abgeschlossen werden konnte? aber auch dann sollte m.E. ein csv angelegt werden, es ist ja ein Eintrag in der Auflistung vorhanden.

**Comment by samuelinniger** [comment]
Inzwischen habe ich drei Durchführungen/Resultate in der Ansicht. Wenn ich nun auf "Als csv exportieren" klicke, Whoopst ILIAS.

<img width="800" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/3cfe31cb-0119-4894-bc32-cc2b70dcb2b1">

**Comment by okaufman** [comment]
gefixt

**Comment by samuelinniger** [comment]
Ich erhalte weiterhin die Meldung: 

 Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key 4873

<img width="1279" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/5e15f01c-093c-4786-a22e-2eed2c27087b">

**Comment by okaufman** [comment]
Error kommt jetzt nicht mehr
