### ISSUE TITLE
SEV ILIAS 8: Abschlossene Runs werden im Tab "Resultate" nicht in Spalte "Abgeschlossen" markiert

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#19]
**Describe the bug**
Obschon eine Durchführung/Run abgeschlossen wurde, und der Tn die Resultate gesehen hat, wird die Durchführung im Tab "Resultate" nicht als Abgeschlossen markiert. 

Siehe https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html 

**Screenshots**
<img width="800" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/496cf707-45bf-495c-84a2-c1c403707204">

Steht evtl. in Verbindung mit Bug https://github.com/ilub-unibe-ch/SelfEvaluation/issues/14

**Comment by okaufman** [comment]
funktioniert jetzt
