### ISSUE TITLE
SEV ILIAS 8: Whoops, wenn in Tab "Resultate" ohne Listenanwahl auf "Datensatz löschen" geklickt wird

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#20]
**Describe the bug**
Tritt neu auf: 
Fehlermeldung The value "NULL" can not be transformed into an integer

**To Reproduce**
Klick auf Button "Datensatz löschen", ohne vorgängig einen Testrun in der Liste angewählt zu haben.

**Screenshots**

<img width="1171" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/9367eeba-96b5-4f9b-9ac3-1153f4b57ba8">

<img width="1276" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/ae9376e2-5dd3-4b11-94b4-9015de36e37e">

**Comment by okaufman** [comment]
klappt jetzt auch mit dem fix von #16
