### ISSUE TITLE
SEV ILIAS 8: Import von exportieren SEV (von ILIAS 7) nicht möglich. 

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#21]
**Describe the bug**
Wenn ich SEV von ILIAS 7 exportiere und auf ILIAS-Next in ILIAS 8 importiere, passiert entweder gar nichts (SEV A), oder ich erhalte ein Whoops (SEV B).

**To Reproduce**
1. Auf ilias.unibe.ch:
SEV A als XML/ZIP exportieren: https://ilias.unibe.ch/goto_ilias3_unibe_xsev_3029363.html
SEV B als XML/ZIP exportieren: https://ilias.unibe.ch/goto_ilias3_unibe_xsev_670949.html 

2. auf ILIAS-Next
Importieren

<img width="500" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/e640abdc-91f4-4beb-aa43-0c821206682e">

Siehe Video (Zuerst Import SEV A, dann Import SEV B)

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/0ecbf9b4-64e4-4874-9a7f-3e18148adcf5

**Additional context**

Fehlermeldung beim Import von SEV B:
ilub\plugin\SelfEvaluation\Question\Meta\MetaQuestion::enableRequired(): Argument #1 ($status) must be of type int, bool given, called in /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/SelfEvaluation/src/Question/Meta/MetaQuestion.php on line 89

**Comment by okaufman** [comment]
gifxt
