### ISSUE TITLE
SEV ILIAS 8: Fragen in Frageblöcken: Fragetext wird nicht angezeigt, wenn Frage bearbeitet wird. Änderungen werden nicht übernommen.

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#22]
**Describe the bug**
Wenn ich eine bereits eingerichtete Frage in einem Frageblock bearbeiten möchte, wird mir der Fragetext NICHT angezeigt. Aucht wird mir der Wert "Umgekehrte Skala" nicht angezeigt.  Neu eingegebene Werte scheinen auch nicht übernommen zu werden.

**To Reproduce**
1. Frage in Frageblock einrichten und die Checkbox "Umgekehrte Skala" aktivieren. Speichern.
2. Zurück in die Frageblockübersicht gehen und mit "Aktionen" --> "Frage bearbeiten" den Editiermodus der Frage öffnen
3. BUG: die zuvor eingegebenen Werte sind nicht sichtbar. 

**Screenshots**

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/5a7cb6b4-9442-43c0-8c61-d1e01219a017

**Comment by okaufman** [comment]
gefixt
