### ISSUE TITLE
SEV-ILIAS 8: Resultate-Ansicht: für die Frageblöcke werden keine Balkendiagramme, Spinnengrafiken oder Links-Rechts Profile angezeigt

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#23]
Siehe Screenshot, getestet hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html

Im Rückmeldungen-Tab werden den Tn nur in der **Übersicht** Grafiken angezeigt. 
Die Grafiken bei den Frageblöcken fehlen.

<img width="1178" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/f58fd269-3369-4812-809f-94b87c91b560">

**Comment by okaufman** [comment]
fixed
