### ISSUE TITLE
SEV ILIAS8: Whoops, wenn Tn eine nicht obligatorische Frage NICHT beantwortet

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#24]
Siehe Video.
Der Tn lässt ein nicht obligatorisches Feld aus und klickt auf "Weiter".

Getestet hier:  https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html

Fehlermeldung: The value "array ( 'question_0' => 'scale_0', 'question_1' => 'scale_0', )" could not be transformed into a string

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/9022ac28-4abc-470e-9175-bf955d30e416

<img width="800" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/f7d9bffc-9f62-4728-b1ed-85bc00a71f60">

**Comment by okaufman** [comment]
Dies klappt jetzt
