### ISSUE TITLE
SEV ILIAS8: Beim Export/Import eines SEV werden die Einstellungen nicht übernommen

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#25]
**Describe the bug**
Beim Export/Import eines einzelnen SEV werden die definierten Einstellungen/Checkboxen nicht übernommen.
--> Die Checkboxen im Tab "Einstellungen" sind alle leer. 

Exportiertes SEV: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577393.html
Importiertes SEV: https://ilias-next.unibe.ch/goto_ilias3_unibe_fold_2577723.html

**Comment by okaufman** [comment]
gefixt

**Comment by samuelinniger** [comment]
Einige Einstellungen werden verändert exportiert/importiert.
Beispiele beim Export/Import mit diesem SEV: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577393.html

Links Import, rechts das Original (exportierte SEV)

1. Checkbox Online und Checkbox Identitätswahl sind nach export/import deaktiviert

<img width="1200" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/83e847d9-d88a-41d8-b899-738909aa96cb">

2. Dropdown-Auswahl unter "Darstellung der Blöcke" ist verändert

<img width="1200" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/4efc95c2-8ccb-4a8e-8140-f5adaae2183b">

3. Checkboxen im Bereich "Darstellung in der Auswertunt" sind verändert

<img width="1200" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/5e7abf33-f520-4ff5-8694-489e687474ea">

**Comment by samuelinniger** [comment]
Beim Export/Import wird zudem bei allen Fragen automatisch der Wert "Umgekehrte Skala" aktiviert.

**Comment by okaufman** [comment]
Geht jetzt.
Umgekehrte skala wird korrekt gesetzt und Settings werden übernommen

**Comment by samuelinniger** [comment]
ist die Änderung bereits eingespielt? Einstellungen werden bei mir weiterhin verändert importiert.

**Comment by Amstutz** [comment]
Should be fixed, except online/offline -> is offline per default afaik.
