### ISSUE TITLE
SEV ILIAS 8 & ILIAS 7: Es ist nicht möglich, im Übersichtsbereich nur das Gesamtfeedback anzeigen zu lassen

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#26]
**Describe the bug**
Einstellungstab, Punkt:  "Feedback-Übersichtsbereich anzeigen".

Bug: Wird an dieser Stelle **nur** die Option "Gesamtfeedback anzeigen" aktiviert, erscheint das Gesamtfeedback **nicht** in der Resultate-Darstellung. Der Feedback-Übersichtsbereich erscheint dann gar nicht mehr in den einzelnen Resultate-Darstellung. Es wird direkt das Feedback zum ersten Frageblock angezeigt. 

<img width="976" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/efff6289-c963-4a39-b6cd-404f2c147dc5">

**Comment by okaufman** [comment]
Ich bin mir unsicher, ob das auch mit dem fix für #23 gelöst wurde. Kannst du mal nachtesten?

**Comment by samuelinniger** [comment]
Ist leider noch nicht gefixt, merci fürs erneute Anschauen

**Comment by okaufman** [comment]
Jetzt sollte dies klappen
