### ISSUE TITLE
SEV ILIAS 8: Es ist nicht möglich, in den Resultaten bei den einzelfeedbacks nur die Spinnengrafik anzeigen zu lassen

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#27]
**Describe the bug**
Einstellungstab, Punkt: "Einzelfeedback-Grafiken anzeigen".

Es ist nicht möglich, nur die Spinnengrafik anzeigen zu lassen. Das Feld bleibt dann leer. 

<img width="755" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/fb8fcf6a-546b-4c07-970f-7dc0bc6ecb51">

In der Resultate-Darstellung: 
<img width="750" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/13b35ca2-d466-4b46-89d9-f3621863408e">

Steht evtl. in Verbindung mit https://github.com/ilub-unibe-ch/SelfEvaluation/issues/23?

**Comment by okaufman** [comment]
fixed
