### ISSUE TITLE
SEVSEV ILIAS 8: neuer Whoops, wenn Tn Stammdatenblock ausfüllt (Problem wohl  bei einer Matrixfrage)

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#29]
**Describe the bug**
Beim Ausfüllen des Stammdatenblock wird den Tn nun auf einmal eine Whoops-Nachricht angezeigt. Ich hatte dem Stammdatenblock nachträglich eine Matrixfrage hinzugefügt.
Getestet hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577393.html
Die hinzugefügte Frage ist die "FrageMaxtrix" im Stammdatenblock 1.
Vermutlich rührt die Fehlermeldung daher, dass in der Matrixfrage unter "Skala" ein Text und keine Zahl eingegeben wurde?

**Additional context**
Fehlermeldung: 
The value "array ( 'question_0' => 'scale_2', 'question_1' => 'scale_2', 'question_2' => 'scale_2', )" could not be transformed into a string

**Screenshots**

<img width="1512" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/1c7854be-84eb-4858-bf36-81759712bc36">

**Comment by thielanja** [comment]
Fehler tritt auch ohne Stammblock und ohne Matrixfrage auf: 
https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577776.html

**Comment by okaufman** [comment]
Das tritt jetzt auch nicht mehr auf mit dem Fix von #24

**Comment by samuelinniger** [comment]
Danke, tritt nun nicht mehr auf - re-Test erfolgreich
