### ISSUE TITLE
SEV ILIAS 8: Statistiken (bspw. das Arithmet. Mittel) werden nicht in .csv Datei exportiert

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#30]
**Describe the bug**
in der exportierten .csv Datei erscheinen aktuell die Statistiken nicht, obwohl sie im Einzelresultat (Tab Resultate) angezeigt werden: 

Screenshot der Statistik (sie werden im Einzelresultat angezeigt/gerechnet):
<img width="716" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/4ec67510-d91b-4094-ae6e-7463143d8444">

Sreenshot .csv-Datei: die entsprechenden Felder bleiben leer. 
<img width="1000" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/df41559d-dadb-4311-9557-6188d4d849b2">

**Comment by okaufman** [comment]
gefixt
