### ISSUE TITLE
ILIAS-8 Version SEV: Diverse Issues bei automat. Sortierung mittels Klick auf den Spaltentitel (Listenansichten Feedbacks, Frageblöcke und Stammdatenblöcke) 

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#7]
**Describe the bug**
Diverse Issue bei der Benutzung der automatischen Sortierfunktion (A-Z bzw. Z-A) mittels Klick auf den Spaltentitel

Siehe angehängte Video.

Überall: es kann nach der Spalte "Aktionen" sortiert werden (Spalte ist anklickbar) - das sollte nicht sein. 

**Feedbacks (Gesamtfeedback und Feedbacks)**
- Sortierfunktion ist bei allen Spalten Fehlerhaft

**In einem Frageblock**
- Sortierung funktioniert in der Spalte "Frage"
- In allen anderen Spalten ist die Sortierfunktion fehlerhaft

**in einem Stammdatenblock**
- Sortierung funktioniert in der Spalte "Kurztitel"
- In allen anderen Spalten ist die Sortierfunktion fehlerhaft

Was mir auch noch auffällt: 
In der ersten Auflistung beim Aufruf des Tabs "Fragen und Feedbacks" (Anzeige der Frageblöcke und Stammdatenblöcke) fehlt die Spalten-Sortierfunktion. Sonst ist sie aber überall vorhanden.
Um die Handhabung einheitlich zu behalten ist es vermutlich sinnvoll, auch in dieser Ansicht die Sortierung über Spaltentitel zu aktivieren?

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/8d3f0466-9e0d-4ab2-a792-6b4e97733eb7

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/464d2b22-72ac-4548-9e2a-68f59cb009e4

https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/2d6f6189-fc99-48fb-b993-3b118e7f6ddb

**Comment by okaufman** [comment]
Ich habe die Sortierung geifxt. auf der ersten Seite ist aber immer noch die Sortierung deaktiviert

**Comment by samuelinniger** [comment]
Beim Re-Test sind mir noch folgende Probleme aufgefallen: 

**Bei den Sortierungen in Feedbacks:**
Die Sortierung des Werts "<= 100%" in der Spalte "Bis" ist noch falsch. 
<img width="178" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/31a73ca3-ab7c-4ee0-996b-98f4dace4d94">

**In Frageblöcken:** 
In der Spalte "Kurztitel" kann die Sortierreihenfolge nicht geändert werden (beim Klick auf den Spaltentitel)
<img width="225" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/ec1dec51-b00a-482b-a199-c560e4cc1bae">

**In Stammdatenblöcken**
In der Spalte "Typ" wird nicht alphabetisch sortiert. 
<img width="281" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/fc0bdd58-dcc1-4e01-9e78-5a3813642042">

**Comment by Amstutz** [comment]
Hi Samuel

Wir verwenden in diesen Tabellen den default Sortiermechanismus. Der ist leider etwas eingeschränkt. Man könnte das ändern und die Sortierung manuell implementieren, ich denke aber hier lohnt sich der mehraufwand nicht.

Bei den Sortierungen in Feedbacks:
--> Die Sortierung ist alphabetisch hier. Lässt sich nicht einfach ändern. Somit stimmt sie, wenn auch im Fall von 100% nicht sehr intuitiv.

In Frageblöcken:
--> Der Titel ändert je nach Einstellung/Config der Frage, dies lässt sich nicht sinnvoll automatisiert sortieren. Sortierung ausgeschaltet.

In Stammdatenblöcken
--> Hier wird nach Typ ID sortiert. Das ist eine Zahl im Hintergrund. Für Nutzerinnen und Nutzer ist das nicht hilfreich. Sortierung augeschaltet.
