### ISSUE TITLE
SEV ILIAS 8: Zugriff als Anonymous: erzeugte Identifkationen lauten "0","1"...

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/SelfEvaluation#9]
**Describe the bug**
Wenn ein Anonymous auf ein SEV zugegreift und in den Einstellungen die Option "Identitätsauswahl " aktiviert ist, sollte das SEV Plugin ein Code erzeugen. 

Bei meinem Test (Zugriff als Anonymous), wurde der Zugriffscode "0" erzeugt. Das ist wohl ein Bug? 
Beim zweiten Zugriff ist es die Nr. "1".

**To Reproduce**
1. im Uninetz auf https://ilias-next.unibe.ch/goto_ilias3_unibe_xsev_2577410.html klicken. 
2. Einen neuen Durchlauf starten

**Expected behavior**
Der Code sollte nicht reproduzierbar sein. In älteren Versionen waren die Codes z.B. "AF8A22"

**Screenshots**
<img width="371" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/06cf6961-0a8e-4ebf-926f-012a4cdc6052">

**Comment by okaufman** [comment]
Bei mir kommt jetzt 3311.
Bitte nachtesten.

**Comment by samuelinniger** [comment]
Während mehreren Versuchen erhielt ich jetzt mehrstellige Zahlen.  
Jetzt aber plötzlich wieder eine "0". Wurden die Codes ersetzt?

<img width="442" alt="grafik" src="https://github.com/ilub-unibe-ch/SelfEvaluation/assets/60101424/38da4774-076d-4dae-8c1e-8b8cee3f301b">

**Comment by okaufman** [comment]
gefixt.
Das Problem war, dass ein Typecast auf int durchgeführt wurde. In dem Identifier konnten aber auch Buchstaben vorkommen. Dies führte zu Problemen.
